import * as React from 'react';
import Head from 'next/head'
import Container from 'react-bootstrap/Container';
import Navbar from 'react-bootstrap/Navbar';
import { useState } from 'react';
import apiClient from '@/apiClient';
import { Grid, Typography } from '@mui/material';
import { useRouter } from 'next/router'
import Gallery from '@/components/gallery';


export default function RutasUsuario() {
  const router = useRouter()
  const [data, setData] = useState(undefined)

  React.useEffect(() => {
    if(router.query.slug){
      apiClient.get(`/schedules/${router.query?.slug}`)
      .then((response) =>{
        console.log(response.data);
        setData(response.data)
      }).catch((error) =>{
        console.log(error);
      })
    }
  }, [router])

  
  return (
    <>
      <Head>
        <title>SIRTA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
      </Head>
      <main>
      <Navbar className="menu">
        <Container>
          <Navbar.Brand id="unidadesTitle" href='/rutas-usuario'>
            {data?.route.origen} - {data?.route.destino}
          </Navbar.Brand>
        </Container>
      </Navbar>
      <Container>
        <Typography variant="h5">
          Visita estos lugares en {data?.route.destino}
        </Typography>
        {data && data?.gallery && (
          <Gallery
            basePath="http://localhost:3000/api/documents/view?file="
            gallery={data.gallery}
          />
        )}
      </Container>
      </main>
    </>
  )
}