import * as React from 'react';
import Head from 'next/head'
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import AddButton from '@/components/addButton';
import Enlaces from '@/components/enlaces';
import FormularioCronograma from '@/components/formularioCronograma';
import CardCronoAdmin from '@/components/cardCronoAdmin';
import { useState } from 'react';
import apiClient from '@/apiClient';
import { Grid } from '@mui/material';
import { useEffect } from 'react';


export default function CronogramaAdmin() {
  const [schedules, setCronograma] = useState([]);

 
 

  useEffect(() => {
    // ir por los productos desde el backend
    apiClient.get('/schedules')
    .then(response => {
      console.log(response.data);
      setCronograma(response.data || []);
    })
    .catch(error => { 
      console.log(error);
    })
  }, []);

  const renderCronograma = () => {
    return schedules.map((crono, index) => (
      <Grid item xs={12} lg={4} xl={2} mt={4} key={crono.id}>
        <CardCronoAdmin
          index={index}
          crono={crono}
        />
      </Grid>
    ))
  }; 

  return (
    <>
      <Head>
        <title>SIRTA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"/>
      </Head>
      <main>
      <Navbar className="menu" fixed="top">
        <Container>
          <Navbar.Brand id="unidadesTitle">
            Cronograma
          </Navbar.Brand>
        </Container>
      </Navbar>
      <Container className="formularioCrono">
        <FormularioCronograma ></FormularioCronograma>
      </Container> 
        <Grid container spacing={2} mt={0}>
            {renderCronograma()}
        </Grid>
      <Enlaces></Enlaces>
      </main>
      
    </>
  )
}
