import Head from "next/head";
import Link from "next/link";
import { useSession } from "next-auth/react";
import Container from 'react-bootstrap/Container';
import Navbar from 'react-bootstrap/Navbar';
import Nav from 'react-bootstrap/Nav';

export default function FirstPost() {
  const { data: session, status } = useSession();
  console.log(session);
  // If no session exists, display access denied message
  if (!session) {
    return (
      <>
        <Head>
          <title>Acerca de</title>
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"/>
        </Head>
        <main>
        <Navbar className="menu" fixed="top">
          <Container>
            <Navbar.Brand id="unidadesTitle">
              Prueba
            </Navbar.Brand>
          </Container>
        </Navbar>
        <div style={{marginTop: "100px", textAlign: "center"}}>
          <h1>Acceso denegado</h1>
        </div>
        </main>
      </>
    )
  }

  return (
    <>
      <Head>
        <title>Acerca de</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"/>
      </Head>

      <main>
      <Navbar className="menu" fixed="top">
        <Container>
          <Navbar.Brand id="unidadesTitle">
            Prueba
          </Navbar.Brand>
        </Container>
      </Navbar>
      <div style={{marginTop: "100px", textAlign: "center"}}>
        <h1>Acerca de nosotros</h1>
        <Link href="/">Inicio</Link>
      </div>
      </main>
    </>
  )
}