import * as React from 'react';
import { Button, Container, Grid, TextField, Typography } from "@mui/material";
import DirectionsBusIcon from '@mui/icons-material/DirectionsBus';
import Box from '@mui/material/Box';
import Head from 'next/head';
import Link from 'next/link';
import apiClient from '@/apiClient';
import { useForm } from 'react-hook-form';
import Swal from 'sweetalert2';

function Restore() {

  const { register, handleSubmit,  formState: { errors }, setError, reset} = useForm();
  const onSubmit = (data) => {
    console.log(data);
    apiClient.post('/password/recover', data)
      .then((response) => {
        Swal.fire({
          position: 'center',
          icon: 'success',
          text: response.data.message,
        })
        reset()
      })
      .catch((error) => {
        console.log(error);
        Swal.fire({
          position: 'center',
          icon: 'error',
          text: error.response.data.message,
        })
        if (error.response.data.errors) {
          error.response.data.errors.forEach((errorItem) => {
            setError(errorItem.field, {
              //error: true,
              type: "validation",
              message: errorItem.error
            });
          })
        }
      });
  }
  return (
    <>
      <Head>
        <title>SIRTA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
      </Head>

      <Container>
        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <div style={{ marginTop: "60px", height: "130px", width: "130px", borderRadius: '50%', backgroundColor: '#1976d2' }}>
            <DirectionsBusIcon style={{ fontSize: '100px', color: 'white', fontWeight: 'bold', marginTop: '18px', marginLeft: '16px' }}>
            </DirectionsBusIcon>
          </div>
        </div>
        <Grid item xs={12} md={8} >
          <Typography variant="h4" mt={6} sx={{ textAlign: 'center', fontWeight: "bold", }}>
            ¡Bienvenido!
          </Typography>
          <Typography className='leyend' variant="h6" mt={6} sx={{ textAlign: 'center' }}>
            Ingresa tu correo electrónico para obtener un enlace de recuperación
          </Typography>
        </Grid>

        <Box component="form" onSubmit={handleSubmit(onSubmit)}>
          <Grid container spacing={4} sx={{ display: 'flex', justifyContent: 'center', marginBottom: 4, marginTop: -10 }}>
            <Grid item xs={12} md={8} sx={{ my: 3 }}>
              <Typography color="primary" variant="h5" mt={6} sx={{ fontWeight: "bold" }}>
                Correo electrónico
              </Typography>
              <TextField
                variant="standard"
                id="input-with-icon-textfield"
                fullWidth
                error={!!errors.email}
                helperText={errors.email?.message}
                {...register('email',
                  {
                    required: 'El email es obligatorio',
                    pattern: {
                      value: /(.+)@(.+){2,}\.(.+){3,}/i,
                      message: 'No es un email Válido'
                    }
                  }
                )
                }
              />

            </Grid>
          </Grid>
          <Grid item xs={12}>
            <Button
              fullWidth
              sx={{ fontSize: "20px" }}
              type="submit"
              variant="contained"
            >
              Enviar enlace
            </Button>
            <Typography className="linkRestore" variant="h6" mt={4} sx={{ textAlign: 'center', fontWeight: "bold" }}>
              ¿Recuerdas tu contraseña? <Link style={{ textDecoration: 'underline', color: '#1976d2' }} href="login">Inicia sesión aquí</Link>
            </Typography>
          </Grid>
        </Box>
      </Container>
    </>
  );
}

export default Restore;