import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import Head from 'next/head';
import Link from 'next/link';
import { BusFront,} from 'react-bootstrap-icons';

function SingIn() {
  return (
    <>
        <Head>
            <title>SIRTA</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"/>
        </Head>
      <main> 
        <Form className="">
            <div className='circulo'>
                <div className='autobus'>
                    <BusFront className="icon"></BusFront>
                </div>
            </div>
           
          <div>
            <h1 className='title'> ¡Bienvenido!</h1>
          </div>
          <p className='leyend'>Ingresa tu correo electrónico para obtener un enlace de recuperación</p>

        <Form.Group className='mb-3' controlId="formBasicEmail">
          <Form.Label className="formGroup-email">Correo electronico</Form.Label>
          <Form.Control className='email' type="email" placeholder="" />
        </Form.Group>
    
        <div className="d-flex justify-content-center">
          <Button type="submit" className='boton'>
            Recuperar
          </Button>
        </div>
        
        <p className="linkRestore">
            ¿Recuerdas tu contraseña? <Link href="SingIn" className='link2'>Inicia sesión aquí</Link>
        </p>

        </Form>
      </main>
        
    </>
  );
}

export default SingIn;