import * as React from 'react';
import Head from 'next/head'
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import AddButtonRutas from '@/components/addButtonRutas';
import Enlaces from '@/components/enlaces';
import Title from '@/components/titulo';
import { useState } from 'react';
import apiClient from '@/apiClient';
import CardRutas from '@/components/cardRutas';
import { Grid } from '@mui/material';

export default function RutasAdmin() {
  const [route, setRoutes] = useState([]);

  React.useEffect(() => {
    refresh();
  }, []);

  const refresh = () => {
    apiClient.get('/routes')
    .then(response =>{
      setRoutes(response.data || []);
    })
    .catch(error => {
      console.log(error);
    })
  }

  const renderRoutes = () => {
    return route.map((routes, index) => (
     <Grid item xs={12} md={4} xl={2} key={routes.id}>
        <CardRutas
          index={index}
          route={routes}
        />
      </Grid>
    ))
  };

  return (
    <>
      <Head>
        <title>SIRTA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"/>
      </Head>
      <main>
      <Navbar className="menu" fixed="top">
        <Container>
          <Navbar.Brand id="unidadesTitle">
            Rutas
          </Navbar.Brand>
          <Nav className="d-flex justify-content-end">
           <AddButtonRutas
            recargar={refresh}
            muestra = "hola"
           />
          </Nav>
        </Container>
      </Navbar>
      <Container className="formularioCrono">
        <Title></Title>
      </Container>  
      <Container>
        <Grid container spacing={2} sx={{p: 2 }}>
          {renderRoutes()}
        </Grid>
      </Container>
      <Enlaces></Enlaces>
      </main>
      
    </>
  )
}
