import Head from 'next/head'
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import AddButton from '@/components/addButton';
import Enlaces from '@/components/enlaces';
import Title from '@/components/titulo';
import CardRutas from '@/components/cardRutas';

export default function CronogramaAdmin() {
  return (
    <>
      <Head>
        <title>SIRTA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"/>
      </Head>
      <main>
      <Navbar className="menu" fixed="top">
        <Container>
          <Navbar.Brand id="unidadesTitle">
            Rutas
          </Navbar.Brand>
          <Nav className="d-flex justify-content-end">
           <AddButton></AddButton>
          </Nav>
        </Container>
      </Navbar>
      <Container className="formularioCrono">
        <Title></Title>
      </Container>  
      <Container className='card-rutas'>
        <CardRutas></CardRutas>
        <CardRutas></CardRutas>
        <CardRutas></CardRutas>
        <CardRutas></CardRutas>
        <CardRutas></CardRutas>
      </Container>
      <Enlaces></Enlaces>
      </main>
      
    </>
  )
}
