import Head from 'next/head'
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import Enlaces from '@/components/enlaces';
import CardRutasUUsuario from '@/components/cardRutasUser';
import SearchRuta from '@/components/searchRutas';
import { Search } from 'react-bootstrap-icons';

export default function RutasUsuario() {
  return (
    <>
      <Head>
        <title>SIRTA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />


      </Head>
      <main>
        <Navbar className="menu" fixed="top">
          <Container>
            <Navbar.Brand id="unidadesTitle">
              Rutas
            </Navbar.Brand>
            <Nav className="d-flex justify-content-end">
            </Nav>
          </Container>
        </Navbar>
        <Container className="formularioCrono">
          <SearchRuta></SearchRuta>
        </Container>
        <Container>
          <div className="tarjetasAcomodo">
            <CardRutasUUsuario></CardRutasUUsuario>
            <CardRutasUUsuario></CardRutasUUsuario>
            <CardRutasUUsuario></CardRutasUUsuario>
            <CardRutasUUsuario></CardRutasUUsuario>
            <CardRutasUUsuario></CardRutasUUsuario>
          </div>
        </Container>
      </main>

    </>
  )
}
