import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import Head from 'next/head';
import Link from 'next/link';
import { BusFront, EyeSlashFill} from 'react-bootstrap-icons';
import { useState } from 'react';
import { useForm } from 'react-hook-form';

function SingIn() {

  const { register, watch, formState: { errors } } = useForm();
  const onSubmit = (data) => {
    console.log(data);
  } 

  const [validated, setValidated] = useState(false);

  const handleSubmit = (event) => {
    const form = event.currentTarget;
    if (form.checkValidity() === false) {
      event.preventDefault();
      event.stopPropagation();
    }

    setValidated(true);
  };

  return (
    <>
      <Head>
        <title>SIRTA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous"
        />
      </Head>

      <Form noValidate validated={validated} onSubmit={handleSubmit}>
        <div className="circulo">
          <div className="autobus">
            <BusFront className="icon"></BusFront>
          </div>
        </div>

        <div>
          <h1 className="title"> ¡Bienvenido!</h1>
        </div>
        <Form.Group className="mb-3" controlId="formBasicEmail">
          <Form.Label className="formGroup-Login">
            Correo electronico
          </Form.Label>
          <Form.Control 
            className="email" type="email" placeholder=""
            id="email"
            error={!!errors.email}
            helperText={errors.email?.message}
            {
               ...register("email", {
                 required: 'Este campo es obligatorio',
                 pattern: {
                  value: /(.+)@(.+){2,}\.(.+){2,}/i,
                  message: 'No es un email valido.'
                }
               })
            } 
          />
        </Form.Group>

        <Form.Group className="mb-3" controlId="formBasicEmail">
          <Form.Label className="formGroup-Login">Contraseña</Form.Label>
          <Form.Control className="password" type="password" placeholder="" />
          <EyeSlashFill className="eyeFill"></EyeSlashFill>
        </Form.Group>

        <div className="d-flex justify-content-center">
          <Button type="submit" className="boton">
            Ingresar
          </Button>
        </div>

        <p className="link">
          ¿No tienes usuario?{" "}
          <Link href="restore" className="link2">
            Registrate aquí
          </Link>
        </p>
      </Form>
    </>
  );
}

export default SingIn;